---
- name: "[{{ name }}] Конфигурация  секрет"
  block:
    - name: "[{{ name }}] Создаём секрет"
      include: "../secret.yml"

  rescue:
    - name: "[{{ name }}] удаляем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "[{{ name }}] Создаём секрет"
      include: "../secret.yml"

- name: "[{{ name }}] Выкладываем сервис"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: localhost:5000/api:latest
        state: present
        networks:
          - name: "{{ networkName }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3002
            target_port: 3000
        secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"