---
- name: "[{{ name }}] Создаём секрет"
  vars:
    envFile: "{{ lookup('file', '{{ name }}/.env.j2') }}"
  community.docker.docker_secret:
    name: "{{ name }}.env.j2"
    data: "{{ envFile | b64encode }}"
    labels:
      secret: "{{ envFile | hash('sha1') }}"
    data_is_b64: true
    state: present