---
- name: создание сети
  community.docker.docker_network:
    name: app_network
    driver: overlay

- name: Выкладка сервисов
  include: "../services/{{ item }}/services.yml"
  vars:
    - name: "{{ item }}"
  loop: "{{ services }}"